language: julia
os:
  - linux
julia:
  - latest
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Test"); cd(Pkg.dir("Bobby")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
matrix:
  fast_finish: true