language: julia
os:
  - linux
julia:
  - 1
notifications:
  email: false
after_success:
  - julia -e 'import Pkg; Pkg.add("Test"); cd(Pkg.dir("Bobby")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
matrix:
  fast_finish: true