language: julia
os:
  - linux
julia:
  - 1
notifications:
  email: false
script:
  - julia --project -e 'import Pkg; Pkg.build(); Pkg.test("Bobby"; coverage=true)'
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage");'
  - julia --project -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'
matrix:
  fast_finish: true